routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('register', 'AuthenticationController@register')->name('admin.auth.register');
Route::post('register', 'AuthenticationController@handleRegister')->name('admin.auth.register');

Route::get('logout','AuthenticationController@logout')->name('admin.auth.logout');

Route::get('login','AuthenticationController@login')->name('admin.auth.login');
Route::post('login','AuthenticationController@handleLogin')->name('admin.auth.login');


Route::group(['prefix' => 'admin'], function () {


    Route::get('/', function () {
        return view('Admin.index');
    })->name('admin.dashboard');


    /**
     * author: Thuantruong
     *
     */
    Route::resource('/topic', 'TopicController');

    /**
     * author: Thuantruong
     *
     */
    Route::resource('/post', 'PostController');




});

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use App\Model\Post;
use App\Model\Topic;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TopicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $topics = Topic::orderBy('created_at','desc')->paginate(10);
        return view('Admin.Topic.index',['topics'=>$topics]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('Admin.Topic.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'name'=>'required'
        ],[
            'name.required'=>'Please Enter Name'
        ]);

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'topic-'.time().'.'.$request->image->getClientOriginalExtension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('failed','Create Fialed');
            }
        }

        $topic = new Topic();
        $topic->name = $request->name;
        $topic->slug = Str::slug($request->name,'-');
        $topic->image = $fileName;
        $topic->save();

        return redirect()->back()->with('success','Created Successfully');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function show(Topic $topic)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function edit(Topic $topic)
    {
        //
        return view('Admin.Topic.edit',['topic'=>$topic]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Topic $topic)
    {
        //
        $request->validate([
            'name'=>'required'
        ],[
            'name.required'=>'Please Enter Name'
        ]);

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'topic-'.time().$request->image->extension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                return redirect()->back()->with('failed','Update Failed');
            }
        }

        $topic->name = $request->name;
        $topic->slug = Str::slug($request->name,'-');
        if($request->image){
            $topic->image = $fileName;
        }
        $topic->save();

        return redirect()->back()->with('success','Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic $topic)
    {
        //
        try {
            //code...
            Post::where('topic_id',$topic->id)->delete();
            Topic::where('id',$topic->id)->delete();
        } catch (\Throwable $th) {
            return redirect()->back()->with('failed',$th->getMessage());
        }

        return redirect()->back()->with('success','Delete Successfully');
    }
}

resources/views/Admin/Topic/create.blade.php
@extends('Admin.layouts.master')

@section('content')
@include('Admin.layouts.sidebar')
@include('Admin.layouts.topbar')

<div class="container-fluid">
    <div>
        @if(session()->has('success'))
        <div class="alert alert-success" >
            {{ session()->get('success') }}
        </div>
        @endif
        @if(session()->has('failed'))
        <div class="alert alert-danger" >
            {{ session()->get('failed') }}
        </div>
        @endif
    </div>

    <!-- Default form contact -->
<form class="text-center border border-light p-5" method="POST" action="{{ route('topic.store')}}" enctype="multipart/form-data" >
    @csrf
    <!-- Name -->

    <input name="name" value="{{old('name')}}" type="text" id="defaultContactFormName" class="form-control mb-4 @error('name') is-invalid @enderror" placeholder="Name">
    <div class="custom-file form-control mb-4" id="uploadForm">
        <input name="image" id="file" type="file" class="custom-file-input" id="customFileLang" lang="pl-Pl">
        <label class="custom-file-label" for="customFileLang">Upload Image</label>
    </div>

    <!-- Send button -->
    <button class="btn btn-info btn-block" type="submit">Create</button>

</form>
<!-- Default form contact -->

</div>


@endsection

resources/views/Admin/Topic/edit.blade.php
@extends('Admin.layouts.master')

@section('content')
@include('Admin.layouts.sidebar')
@include('Admin.layouts.topbar')

<div class="container-fluid">
    <div>
        @if(session()->has('success'))
        <div class="alert alert-success" >
            {{ session()->get('success') }}
        </div>
        @endif
        @if(session()->has('failed'))
        <div class="alert alert-danger" >
            {{ session()->get('failed') }}
        </div>
        @endif
    </div>

    <!-- Default form contact -->
<form class="text-center border border-light p-5" method="POST" action="{{ route('topic.update',$topic)}}" enctype="multipart/form-data">
    @method('PUT')
    @csrf
    <!-- Name -->
    <input name="name" value="{{$topic->name}}" type="text" id="defaultContactFormName" class="form-control mb-4 @error('name') is-invalid @enderror" placeholder="Name">

    <div class="custom-file form-control mb-4" id="uploadForm">
        <input name="image" id="file" type="file" class="custom-file-input" id="customFileLang">
        <label class="custom-file-label" for="customFileLang">Upload Image</label>
    </div>
    <img src="{{ asset('uploads/'.$topic->image) }}" width="200" height="200" alt="">

    <!-- Send button -->
    <button class="btn btn-info btn-block" type="submit">Update</button>

</form>
<!-- Default form contact -->

</div>


@endsection

resources/views/Admin/Topic/index.blade.php
@extends('Admin.layouts.master')

@section('content')
@include('Admin.layouts.sidebar')
@include('Admin.layouts.topbar')

<div class="container-fluid">

      <!-- Page Heading -->
      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
      </div>
      <div>
        @if(session()->has('success'))
        <div class="alert alert-success" >
            {{ session()->get('success') }}
        </div>
        @endif
        @if(session()->has('failed'))
        <div class="alert alert-danger" >
            {{ session()->get('failed') }}
        </div>
        @endif
    </div>

      <div class="d-flex flex-row-reverse bd-highlight" >
        <a href="{{ route('topic.create')}}" type="button" class="btn btn-primary">Add New</a>

      </div>
      <table class="table">
        <caption>List of Topic</caption>
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Slug</th>
            <th scope="col">Image</th>
            <th scope="col">Settings</th>

          </tr>
        </thead>
        <tbody>
            @foreach ($topics as $key => $topic)
                <tr>
                    <th scope="row">{{$key}}</th>
                    <td>{{$topic->name}}</td>
                    <td>{{$topic->slug}}</td>
                    <td>
                        <img src={{ $topic->image?asset('uploads/'.$topic->image):asset('uploads/default.jpg') }} width="100" height="100"  alt="" width srcset="">
                    </td>
                    <td>
                        <a href="{{ route('topic.edit',$topic) }}" class="btn btn-primary"><i class="fas fa-edit "></i></a>

                        <a href="#" onclick="document.getElementById('formDelete').submit()" class="btn btn-danger"><i class="fas fa-trash-alt "></i></a>
                        <form hidden id="formDelete" action="{{ route('topic.destroy',$topic) }}" method="post">
                            @csrf
                            @method('DELETE')
                        </form>
                    </td>
                </tr>
            @endforeach


        </tbody>
      </table>

</div>

@endsection