routes/web.php
<?php

use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('register', 'AuthenticationController@register')->name('admin.auth.register');
Route::post('register', 'AuthenticationController@handleRegister')->name('admin.auth.register');

Route::get('logout','AuthenticationController@logout')->name('admin.auth.logout');

Route::get('login','AuthenticationController@login')->name('admin.auth.login');
Route::post('login','AuthenticationController@handleLogin')->name('admin.auth.login');


Route::group(['prefix' => 'admin'], function () {


    Route::get('/', function () {
        return view('Admin.index');
    })->name('admin.dashboard');


    /**
     * author: Thuantruong
     *
     */
    Route::resource('/topic', 'TopicController');

    /**
     * author: Thuantruong
     *
     */
    Route::resource('/post', 'PostController');




});

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Model\Post;
use App\Model\Topic;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class PostController extends Controller
{

    public $topic_id;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //

        $posts = Post::orderBy('created_at','desc')->paginate(20);
        $topics = Topic::all();

        if($topic_id = $request->input('topic')){
            $posts = Post::where('topic_id',$topic_id)->orderBy('created_at','desc')->paginate(10);
        }

        return view('Admin.Post.index',compact(['posts','topics']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $topics = Topic::all();
        return view('Admin.Post.create',['topics'=>$topics]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'name'=>'required',
            'content'=>'required'
        ],[
            'name.required'=>'Please Enter Name',
            'content.required'=>'Please enter content'
        ]);

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'post-'.time().'.'.$request->image->getClientOriginalExtension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                throw $th;
                return redirect()->back()->with('failed','Create Fialed');
            }
        }

        $post = new Post();
        $post->topic_id = $request->topic_id;
        $post->slug = Str::slug($request->name,'-');
        $post->name = $request->name;
        $post->description = $request->description;
        $post->content = $request->content;
        $post->image = $fileName;
        $post->save();

        return redirect()->back()->with('success','Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        //
        $topics = Topic::all();
        return view('Admin.Post.edit',['post'=>$post,'topics'=>$topics]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        //
        $request->validate([
            'name'=>'required',
            'content'=>'required'
        ],[
            'name.required'=>'Please Enter Name',
            'content.required'=>'Please enter content'
        ]);

        $fileName = 'default.jpg';
        if ($request->image) {
            try {
                $fileName = 'post-'.time().'.'.$request->image->getClientOriginalExtension();
                $request->image->move(public_path('uploads'), $fileName);
            } catch (\Throwable $th) {
                return redirect()->back()->with('failed',$th->getMessage());
            }
        }
        $post->topic_id = $request->topic_id;
        $post->slug = Str::slug($request->name,'-');
        $post->name = $request->name;
        $post->description = $request->description;
        $post->content = $request->content;
        if($request->image){
            $post->image = $fileName;
        }
        $post->update();

        return redirect()->back()->with('success','Updated Successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        //
        try {
            $post->delete();
        } catch (\Throwable $th) {
            return redirect()->back()->with('failed',$th->getMessage());
        }

        return redirect()->back()->with('success','Delete successfully');

    }
}

resources/views/Admin/Post/create.blade.php
@extends('Admin.layouts.master')


<script src="{{ asset('ckfinder/ckfinder.js') }}"></script>
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>

@section('content')
@include('Admin.layouts.sidebar')
@include('Admin.layouts.topbar')

<div class="container-fluid">
    <div>
        @if(session()->has('success'))
        <div class="alert alert-success" >
            {{ session()->get('success') }}
        </div>
        @endif
        @if(session()->has('failed'))
        <div class="alert alert-danger" >
            {{ session()->get('failed') }}
        </div>
        @endif
    </div>

    <!-- Default form contact -->
<form class="text-center border border-light p-5" method="POST" action="{{ route('post.store')}}" enctype="multipart/form-data" >
    @csrf
    <!-- Name -->
    <div class="row">
        <div class="col">
            <select name="topic_id" class="custom-select custom-select-md mb-4">
                <option selected>Open this select menu</option>
                @foreach ($topics as $topic)
                    <option value="{{$topic->id}}">{{$topic->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="col">
            <input name="name" value="{{old('name')}}" type="text" id="defaultContactFormName" class="form-control mb-4 @error('name') is-invalid @enderror" placeholder="Name">

        </div>
    </div>


    <!--Textarea with icon prefix-->
    <div class="md-form amber-textarea mb-4">
        <label class="float-left" for="">Description</label>
        <textarea name="description" id="form24" class="md-textarea form-control" rows="3">
            {{old('description')}}
        </textarea>
    </div>
    <div class="custom-file form-control mb-4" id="uploadForm">
        <input name="image" id="file" type="file" class="custom-file-input" id="customFileLang" lang="pl-Pl">
        <label class="custom-file-label" for="customFileLang">Upload Image</label>
    </div>
    <textarea name="content" id="editor" class="mb-4">
        {!!old('content')!!}
    </textarea>
    <br>
    <!-- Send button -->
    <button class="btn btn-info btn-block" type="submit">Create</button>

</form>
<!-- Default form contact -->

</div>

<script type="text/javascript">

        CKEDITOR.replace( 'editor',{
            filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
            filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
            filebrowserWindowWidth: '1000',
            filebrowserWindowHeight: '700'
        });

</script>

@endsection

resources/views/Admin/Post/edit.blade.php
@extends('Admin.layouts.master')


<script src="{{ asset('ckfinder/ckfinder.js') }}"></script>
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>

@section('content')
@include('Admin.layouts.sidebar')
@include('Admin.layouts.topbar')

<div class="container-fluid">
    <div>
        @if(session()->has('success'))
        <div class="alert alert-success" >
            {{ session()->get('success') }}
        </div>
        @endif
        @if(session()->has('failed'))
        <div class="alert alert-danger" >
            {{ session()->get('failed') }}
        </div>
        @endif
    </div>

    <!-- Default form contact -->
<form class="text-center border border-light p-5" method="POST" action="{{ route('post.update',$post)}}" enctype="multipart/form-data" >
    @csrf
    @method('PUT')
    <!-- Name -->
    <div class="row">
        <div class="col">
            <select name="topic_id" class="custom-select custom-select-md mb-4">
                @foreach ($topics as $topic)
                    @if ($topic->id == $post->topic->id)
                        <option selected value="{{$topic->id}}">{{$topic->name}}</option>
                    @else
                        <option value="{{$topic->id}}">{{$topic->name}}</option>
                    @endif
                @endforeach
            </select>
        </div>
        <div class="col">
            <input name="name" value="{{$post->name}}" type="text" id="defaultContactFormName" class="form-control mb-4 @error('name') is-invalid @enderror" placeholder="Name">

        </div>
    </div>
    <!--Textarea with icon prefix-->
    <div class="md-form amber-textarea mb-4">
        <label class="float-left" for="">Description</label>
        <textarea name="description" id="form24" class="md-textarea form-control" rows="3">
            {{ $post->description }}
        </textarea>
    </div>
    <div class="custom-file form-control mb-4" id="uploadForm">
        <input name="image" id="file" type="file" class="custom-file-input" id="customFileLang" lang="pl-Pl">
        <label class="custom-file-label" for="customFileLang">Upload Image</label>
    </div>
    <img src="{{ $post->image?asset('uploads/'.$post->image):asset('uploads/default.jpg') }}" class="mb-4" width="200" height="200" alt="" srcset="">

    <textarea name="content" id="editor" class="mb-4">
            {!! $post->content !!}
    </textarea>
    <br>
    <!-- Send button -->
    <button class="btn btn-info btn-block" type="submit">Update</button>

</form>
<!-- Default form contact -->

</div>

    <script type="text/javascript">

            CKEDITOR.replace( 'editor',{
                filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
                filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
                filebrowserWindowWidth: '1000',
                filebrowserWindowHeight: '700'
            });

    </script>

@endsection

resources/views/Admin/Post/index.blade.php
@extends('Admin.layouts.master')

@section('content')
@include('Admin.layouts.sidebar')
@include('Admin.layouts.topbar')

<div class="container-fluid">

      <!-- Page Heading -->
      <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
      </div>
      <div>
        @if(session()->has('success'))
        <div class="alert alert-success" >
            {{ session()->get('success') }}
        </div>
        @endif
        @if(session()->has('failed'))
        <div class="alert alert-danger" >
            {{ session()->get('failed') }}
        </div>
        @endif
    </div>

      <div class="d-flex flex-row-reverse bd-highlight" >
        <a href="{{ route('post.create')}}" type="button" class="btn btn-primary">Add New</a>

      </div>
      <table class="table">
        <caption>List of Post</caption>
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">
                <select name="" id="topic_display" onchange="myFunction()">
                    <option value="" selected>TOPIC</option>
                    @foreach ($topics as $topic)
                        <option value="{{$topic->id}}">{{$topic->name}}</option>
                    @endforeach
                </select>
                <script>
                    function myFunction(){
                        let idtp = document.getElementById('topic_display').value;
                        location.href = location.href + `?&topic=${idtp}`;
                    }
                </script>

            </th>
            <th scope="col">Slug</th>
            <th scope="col">Viewer</th>
            <th scope="col">Image</th>
            <th scope="col">Settings</th>

          </tr>
        </thead>
        <tbody>
            @foreach ($posts as $key => $post)
                <tr>
                    <th scope="row">{{$key}}</th>
                    <td>{{$post->name}}</td>
                    <td><a href="{{ route('post.index', ['topic'=>$post->topic->id]) }}" class="btn btn-outline-primary">{{$post->topic->name}}</a></td>
                    <td>{{$post->slug}}</td>
                    <td>{{$post->viewer}}</td>
                    <td>
                        <img src="{{ $post->image?asset('uploads/'.$post->image):asset('uploads/default.jpg') }}" width="100" height="100" alt="" sizes="100" srcset="">
                    </td>
                    <td>
                        <a href="{{ route('post.edit',$post) }}" class="btn btn-primary"><i class="fas fa-edit "></i></a>
                        <a href="#" onclick="document.getElementById('formDelete').submit()" class="btn btn-danger"><i class="fas fa-trash-alt "></i></a>
                        <form hidden id="formDelete" action="{{ route('post.destroy',$post) }}" method="post">
                            @csrf
                            @method('DELETE')
                        </form>
                    </td>
                </tr>
            @endforeach


        </tbody>
      </table>
      <div style="display:flex;justify-content: center">
          {{$posts->links()}}
      </div>
</div>

@endsection